path: "D:/Program/AI-Assisted Scrap Detection And Weight Estimation/backend/datasets/full_dataset_box"
train: images/train
val: images/val
test: images/test
names:
  0: cast_iron
  1: cloth
  2: gas_cylinder
  3: dust
  4: pitted_sheets
  5: left_over_paint
  6: plastics
  7: rubber
  8: tin
  9: water
  10: wood
